### PR TITLE
Fix file paths on Windows

### PR DESCRIPTION
**Pull request by Haffi921**
Here's the fix that works on my end. Like I said, this is your repo so I don't mind you rejecting the pull request and fixing the issue yourself. This is mainly to point out what I did. Hope this helps :)

…L' class

The 'url.fileURLToPath' function provides the correct path for all platforms (including Windows).
This corrects the builderDir glob bug.

fdd3224

### CODE REVIEW

**Comment by bjoluc** [comment]
Thanks! If you don't mind, I'll try to get the CI passing on this PR so we can merge it :)

**Comment by bjoluc** [comment]
It looks like asset watching is not working on MacOS and Windows. Don't worry, that's certainly unrelated – I never ran the CI on anything but Linux before...

**Comment by Haffi921** [comment]
Alright, I have a macbook too so I can investigate this a bit. I'll check on Windows first, let you know what I find.

**Comment by bjoluc** [comment]
> Alright, I have a macbook too so I can investigate this a bit. I'll check on Windows first, let you know what I find.

Wow, that'd be great!

**Comment by bjoluc** [comment]
I just merged my test branch into this one so we can continue here: Decided to consistently convert back slashes to forward slashes since gulp/glob wants it that way. Webpack seems to work with both. Now wondering why `gulp.watch` doesn't work...

**Comment by Haffi921** [comment]
Hmmm weird... I installed this fork on my npm and went through the normal steps of creating a project and running it. When I do `npm start` I get hit by: 
```
File not found with singular glob: /C:/Users/.../jspsych-builder//assets/index.html
```

So there is some other place where the paths are bongled hahah. I'm gonna investigate that, perhaps it will help us with the gulp watch, perhaps not. However, I cannot user test the gulp watch issue until I've resolved this.

**Comment by bjoluc** [comment]
Did you `npm link` your local version?

**Comment by bjoluc** [comment]
> So there is some other place where the paths are bongled hahah.

I hope not :see_no_evil: No idea where that might be...

**Comment by bjoluc** [comment]
Oh, and interestingly, the windows CI job doesn't have the problem: https://github.com/bjoluc/jspsych-builder/runs/4510036258?check_suite_focus=true

**Comment by Haffi921** [comment]
Hmmm wait, when I do `jspsych run` this works, `npm start` does not work. I have to admit I don't see what the difference is. I am doing `npm install -g <local repo>` and up until now it's been responding to my changes in the local repo. Perhaps I am missing something

**Comment by Haffi921** [comment]
Ahhhh ofc, `npm start` uses the local jspsych-builder in `<project>/node_modules` which is downloaded by the global jspsych-builder during `init`. This still has the old `new URL(...)` code hahaha

Edit: Panic over, now I'm gonna check how it responds to me adding items in the watch folder

**Comment by Haffi921** [comment]
It works! Changes to the asset folders are reflected in `.jspsych-builder/media` folder. Also, just for sanity, I tried making a jsPsychImageKeyboardResponse with a reference to a non-existent image. When I added the image, it got copied in the watch folder and appeared on my screen.

So `gulp watch` works, but the test is not working. Or is it? You said this:

> Oh, and interestingly, the windows CI job doesn't have the problem: https://github.com/bjoluc/jspsych-builder/runs/4510036258?check_suite_focus=true

Don't know if you were referring to this issue, but clicking on the link I see the same fail as on macos. Maybe I am misunderstanding you.

I'm going to look a bit at the tests to see if I can spot the issue. It would be great to get it working!

Edit: Ohh wait, "CI job doesn't have **the** problem". Perhaps you meant the `npm start` issue. Now I understand

**Comment by bjoluc** [comment]
> It works! Changes to the asset folders are reflected in .jspsych-builder/media folder.

Great, that's insanely helpful, thanks!

> Perhaps you meant the npm start issue.

:+1: 

Maybe it's related to shelljs and how I use it then. The "tests" don't really deserve the name – there's just a stupid script-like story test that runs every command once and checks the artifacts. I should probably have a few of these scripts and also check for proper errors and stuff. Don't know how to best go about this. Unit testing – while probably possible – doesn't seem too benifitial here, since most of jspsych-builder is just assembling configs for other tools.

**Comment by Haffi921** [comment]
> Maybe it's related to shelljs and how I use it then. The "tests" don't really deserve the name – there's just a stupid script-like story test that runs every command once and checks the artifacts. I should probably have a few of these scripts and also check for proper errors and stuff. Don't know how to best go about this. Unit testing – while probably possible – doesn't seem too benifitial here, since most of jspsych-builder is just assembling configs for other tools.

Yeah exactly, I know what you mean.

Well, just to let you know I did some more testing (on Windows). So while running only half of the `story.js` script up until the server was running, I started node in the terminal and tested creating files with `shelljs`. What I found was that files and folders **are** reflected in the watch folder but not files within folders. Specifically, when I created the folder `test` within `media/images` (like you do in your original script) then that is reflected. However, when I create `1.txt` within that `test` folder, it does not reflect it.

So perhaps gulp is not configured to reflect files within folders? Which is weird because the tests run ok on Linux...

But so actually, if gulp is actually not watching files within folders, then the tests actually worked out weed out a bug hahah. But I get what you mean, I also often feel like this too. But perhaps it _is_ good to have it since you are working on a Linux (?). I don't know though, let's see if there's any validity to this "gulp watch not seeing files within folders" thing.

Edit: Gulp also copies the whole file structure at the when you run the dev server (i.e. all files within all folders, etc.). But it's not responding to changes like that after the server is run.

**Comment by Haffi921** [comment]
For now perhaps, we can change the tests so that it only checks 1st level changes in the asset folders. Then the checks can go through and original changes can be implemented. Leave it up to you to decide ofc :)

**Comment by Haffi921** [comment]
Just saw you started the checks with changes to the test script. Thanks for being so active with this bug fix and accepting my pull request :) I really appreciate this tool and use it at work.

**Comment by bjoluc** [comment]
Thanks for the kind words and for all the help @Haffi921! GH somehow doesn't interpret the `Co-authored-by` in the commit msg, but folks should be smart enough to get that you didn't thank yourself in the message of a squash-merged PR :sweat_smile:

**Pull request merged**
